"""Generates data/books.json and data/tbr.json (source of truth for the book data)."""
import json

G = {
  "prod": "Productivity",
  "self": "Self-Improvement",
  "mkt": "Marketing",
  "ent": "Entrepreneurship",
  "write": "Writing",
  "sci": "Science",
  "psy": "Psychology",
  "fin": "Finance",
  "health": "Health",
  "tech": "Technology & AI",
  "fic": "Science Fiction",
  "photo": "Photography",
  "film": "Film",
  "career": "Career",
  "create": "Creativity & Thinking",
}

def b(slug, title, author, year, g, en, fmt, **extra):
    d = {"slug": slug, "title": title}
    d.update({"author": author, "year": year,
              "genre": G[g],
              "synopsis": en,
              "format": fmt, "image": f"images/covers/{slug}.jpg"})
    d.update(extra)
    return d

READ = [
 b("atomic-habits","Atomic Habits","James Clear",2018,"self",
   "A practical framework for building good habits and breaking bad ones through tiny changes that compound over time, built on four laws: make it obvious, attractive, easy and satisfying.",
   "Physical", rating=4.5, status="highlighted"),
 b("varieties-of-scientific-experience","The Varieties of Scientific Experience","Carl Sagan",2006,"sci",
   "Sagan's 1985 Gifford Lectures, published posthumously: a personal view on science, the cosmos and the search for God, arguing for wonder grounded in evidence.",
   "Libby", status="reading"),
 b("crush-it","Crush It!","Gary Vaynerchuk",2009,"ent",
   "Gary Vee's call to turn your passion into a business by building a personal brand on social media, and the hustle it takes to make it work.",
   "Physical", rating=4.0, status="distilled"),
 b("how-to-take-smart-notes","How to Take Smart Notes","Sönke Ahrens",2017,"prod",
   "An introduction to the Zettelkasten method: how a slip-box of connected, permanent notes turns reading into writing and thinking into a routine.",
   "Libby", rating=5.0, status="highlighted"),
 b("building-a-second-brain","Building a Second Brain","Tiago Forte",2022,"prod",
   "A methodology for capturing, organizing and sharing what you learn in a digital system (CODE and PARA), so your ideas become finished work.",
   "Physical", rating=5.0, status="distilled"),
 b("purple-cow","Purple Cow","Seth Godin",2003,"mkt",
   "Why being remarkable is the only safe marketing strategy: stop blending in with the herd and build products worth talking about.",
   "Physical", rating=4.0, status="highlighted"),
 b("essentialism","Essentialism","Greg McKeown",2014,"prod",
   "The disciplined pursuit of less: how to separate the vital few from the trivial many and say no to everything that isn't essential.",
   "Physical", rating=4.5, status="highlighted"),
 b("psychology-of-money","The Psychology of Money","Morgan Housel",2020,"fin",
   "Nineteen short stories on how behavior, not intelligence, drives financial outcomes, and what timeless lessons say about wealth, greed and happiness.",
   "Libby", rating=4.0, status="highlighted"),
 b("slow-productivity","Slow Productivity","Cal Newport",2024,"prod",
   "The lost art of accomplishment without burnout, built on three principles: do fewer things, work at a natural pace, and obsess over quality.",
   "Physical", rating=4.0, status="read"),
 b("feel-good-productivity","Feel-Good Productivity","Ali Abdaal",2023,"prod",
   "How to do more of what matters by boosting energy rather than forcing discipline, using a framework of play, power and people.",
   "Physical", rating=4.0, status="read"),
 b("getting-things-done","Getting Things Done","David Allen",2001,"prod",
   "The classic system for stress-free productivity: capture everything, clarify what it means, organize it and review it regularly.",
   "Libby", status="reading"),
 b("deep-work","Deep Work","Cal Newport",2016,"prod",
   "Rules for focused success in a distracted world: why the ability to concentrate without distraction is rare, valuable and trainable.",
   "Libby", status="reading"),
 b("sense-of-style","The Sense of Style","Steven Pinker",2014,"write",
   "A cognitive scientist's guide to clear, elegant writing in the 21st century, drawing on linguistics and psychology instead of rigid rules.",
   "Libby", status="reading"),
 b("storynomics","Storynomics","Robert McKee & Thomas Gerace",2018,"mkt",
   "Story-driven marketing in the post-advertising world: how to use the principles of great storytelling to build brands people care about.",
   "Libby", status="reading"),
]

TBR = [
 b("rise-of-the-youpreneur","Rise of the Youpreneur","Chris Ducker",2018,"ent",
   "A guide to building a personal-brand business around who you are, from finding your audience to creating products and a loyal community.",
   "Physical"),
 b("primal-branding","Primalbranding","Patrick Hanlon",2006,"mkt",
   "Argues that strong brands are belief systems, and lays out seven elements (creation story, creed, icon, rituals, sacred words, nonbelievers and leader) that create devoted communities.",
   "Physical"),
 b("business-for-punks","Business for Punks","James Watt",2015,"ent",
   "The BrewDog co-founder's playbook for breaking the rules of business: build a brand with attitude, ignore convention and take on the giants.",
   "Physical"),
 b("sell-like-crazy","Sell Like Crazy","Sabri Suby",2019,"mkt",
   "An Australian growth marketer's step-by-step system for generating leads and sales online, with direct-response tactics and a focus on measurable results.",
   "Physical"),
 b("inner-game-of-tennis","The Inner Game of Tennis","W. Timothy Gallwey",1974,"self",
   "A classic on the mental side of performance: quiet the self-critical mind, trust your body and learn through awareness instead of instruction.",
   "Physical"),
 b("great-photographs","Read This if You Want to Take Great Photographs","Henry Carroll",2014,"photo",
   "A short visual primer that teaches composition, light, exposure and more through the work of great photographers, with no jargon.",
   "Physical"),
 b("this-is-how-you-make-a-movie","This Is How You Make a Movie","Tim Grierson",2021,"film",
   "An accessible, illustrated guide to how films get made, from the initial idea and script through casting, shooting, editing and release.",
   "Physical"),
 b("thinking-fast-and-slow","Thinking, Fast and Slow","Daniel Kahneman",2011,"psy",
   "The Nobel laureate's tour of the two systems that drive how we think, the fast intuitive one and the slow deliberate one, and the biases that trip us up.",
   "Libby"),
 b("almanack-of-naval-ravikant","The Almanack of Naval Ravikant","Eric Jorgenson",2020,"self",
   "A curated collection of Naval Ravikant's ideas on building wealth and finding happiness, compiled from his tweets, essays and interviews.",
   "Libby"),
 b("so-good-they-cant-ignore-you","So Good They Can't Ignore You","Cal Newport",2012,"career",
   "Challenges the 'follow your passion' advice: passion follows mastery, and career capital is what gets you work you love.",
   "Libby"),
 b("recursion","Recursion","Blake Crouch",2019,"fic",
   "A sci-fi thriller about false memory syndrome, a neuroscientist's device and a detective who realizes reality is being rewritten.",
   "Libby"),
 b("digital-minimalism","Digital Minimalism","Cal Newport",2019,"prod",
   "A philosophy of technology use: focus your time on a small number of carefully chosen tools that support what you value, and drop the rest.",
   "Libby"),
 b("tiny-experiments","Tiny Experiments","Anne-Laure Le Cunff",2025,"self",
   "How to live freely in a goal-obsessed world: swap rigid goals for small, curious experiments and learn from the results.",
   "Libby"),
 b("outlive","Outlive","Peter Attia",2023,"health",
   "The science and art of longevity: a framework for extending both lifespan and healthspan through exercise, nutrition, sleep and emotional health.",
   "Libby"),
 b("effortless","Effortless","Greg McKeown",2021,"prod",
   "The follow-up to Essentialism: how to make the most important things easier by removing friction and finding effortless ways to get results.",
   "Libby"),
 b("bullet-journal-method","The Bullet Journal Method","Ryder Carroll",2018,"prod",
   "The creator of the Bullet Journal explains his analog system to track the past, order the present and plan the future.",
   "Libby"),
 b("co-intelligence","Co-Intelligence","Ethan Mollick",2024,"tech",
   "A practical guide to living and working with AI as a collaborator: four rules for co-intelligence and what it means for work, education and creativity.",
   "Libby"),
 b("good-writing","Good Writing","Neal Allen",2026,"write",
   "36 ways to improve your sentences, with examples for each rule and essays on the practicalities of finishing projects and trusting editors.",
   "Libby"),
 b("protocols","Protocols","Andrew Huberman",2025,"health",
   "An operating manual for the human body: science-based protocols for sleep, focus, stress, fitness and more.",
   "Libby"),
 b("jab-jab-jab-right-hook","Jab, Jab, Jab, Right Hook","Gary Vaynerchuk",2013,"mkt",
   "How to tell your story in a noisy social world: give value with several 'jabs' before you land the 'right hook' ask, tailored to each platform.",
   "Kobo Store"),
 b("on-writing-well","On Writing Well","William Zinsser",1976,"write",
   "The classic guide to writing nonfiction: simplicity, clarity, brevity and humanity, with lessons for essays, memoirs, travel and science writing.",
   "Kobo Store"),
 b("write-useful-books","Write Useful Books","Rob Fitzpatrick",2020,"write",
   "A systematic approach to writing nonfiction that actually helps readers, from choosing the outcome to validating the idea and structuring the book.",
   "Kobo Store"),
 b("co-existence","Co-Existence","Ethan Mollick",2026,"tech",
   "Follow-up to Co-Intelligence: on working with AI that is sometimes better than you, keeping your judgment and building a durable human advantage. Out October 20, 2026.",
   "Kobo Store"),
 b("think-like-a-rocket-scientist","Think Like a Rocket Scientist","Ozan Varol",2020,"create",
   "Nine strategies from rocket science, like reasoning from first principles and testing at low risk, that anyone can apply to make giant leaps in work and life.",
   "Kobo Store"),
]

json.dump(READ, open("data/books.json","w"), ensure_ascii=False, indent=2)
json.dump(TBR, open("data/tbr.json","w"), ensure_ascii=False, indent=2)
print(len(READ), len(TBR))
